version: '2'
services:

  sehr_cloud_minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    restart: always
    container_name: sehr_cloud_minio 
    ports:
    - 9000:9000
    volumes:
    - "F:/data:/backup"
    environment:
    - "MINIO_ACCESS_KEY=minioadmin" 
    - "MINIO_SECRET_KEY=minioadmin"
    command: ["server", "/data"]
    networks:
    - sehr_cloud_network

  sehr_cloud_mc:
    image:  minio/mc 
    container_name: sehr_cloud_mc
    restart: always
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    networks:
    - sehr_cloud_network
  
  sehr_cloud_mongodb:
    container_name: sehr_cloud_mongodb
    image: mongo:4.0.4
    restart: always
    ports:
    - 27017:27017
    networks:
    - sehr_cloud_network

  # iehr_cloud_kc: 
  #   image: quay.io/keycloak/keycloak:10.0.1
  #   container_name: iehr_cloud_kc
  #   restart: always
  #   ports: 
  #   - 8080:8080
  #   environment: 
  #   - "KEYCLOAK_USER=admin"
  #   - "KEYCLOAK_PASSWORD=admin"
  #   networks: 
  #   - minio_network

networks:
  sehr_cloud_network: 
    driver: "bridge"

